name: transferencia de arvhicos pipeline

on:
  workflow_dispatch:
    inputs:
      source_ip:
        description: 'IP del servidor origen'
        required: true
      destination_ip:
        description: 'IP del servidor destino'
        required: true
      source_dir:
        description: 'Directorio de origen'
        required: true
      destination_dir:
        description: 'Directorio de destino'
        required: true

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Transfer files
        run: |
          chmod +x ./scripts/transfer.sh
          ./scripts/transfer.sh "${{ github.event.inputs.source_ip }}" "${{ github.event.inputs.source_dir }}" "${{ github.event.inputs.destination_ip }}" "${{ github.event.inputs.destination_dir }}"
