name: Transferencia de Archivos vía SFTP

on:
  workflow_dispatch:
    inputs:
      USER:
        description: "Usuario SSH"
        required: true
      PASSWORD:
        description: "Contraseña SSH"
        required: true
      ORIGIN_IP:
        description: "IP del servidor origen"
        required: true
      DEST_IP:
        description: "IP del servidor destino"
        required: true
      ORIGIN_PATH:
        description: "Ruta origen de los archivos"
        required: true
      DEST_PATH:
        description: "Ruta destino para copiar archivos"
        required: true
      PORT:
        description: "Puerto SSH (por defecto 22)"
        required: false
        default: "22"

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Ejecutar transferencia SFTP
        env:
          SSHPASS: ${{ github.event.inputs.PASSWORD }}
        run: |
          chmod +x ./scripts/transfer.sh
          ./scripts/transfer.sh \
            "${{ github.event.inputs.USER }}" \
            "${{ github.event.inputs.ORIGIN_IP }}" \
            "${{ github.event.inputs.DEST_IP }}" \
            "${{ github.event.inputs.ORIGIN_PATH }}" \
            "${{ github.event.inputs.DEST_PATH }}" \
            "${{ github.event.inputs.PORT }}"
