name: Transfer Files

on:
  workflow_dispatch:
    inputs:
      source_ip:
        description: 'IP del servidor origen'
        required: true
      source_dir:
        description: 'Directorio en servidor origen'
        required: true
      dest_ip:
        description: 'IP del servidor destino'
        required: true
      dest_dir:
        description: 'Directorio en servidor destino'
        required: true
      port:
        description: 'Puerto SSH (opcional)'
        required: false
        default: '22'

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Dar permisos al script
        run: chmod +x pipeline/scripts/transfer.sh

      - name: Ejecutar transferencia
        run: |
          pipeline/scripts/transfer.sh \
            ${{ github.event.inputs.source_ip }} \
            ${{ github.event.inputs.source_dir }} \
            ${{ github.event.inputs.dest_ip }} \
            ${{ github.event.inputs.dest_dir }} \
            ${{ github.event.inputs.port }}
