name: Transfer Files via SFTP

on:
  workflow_dispatch:
    inputs:
      source_ip:
        description: 'IP origen'
        required: true
        default: '192.168.1.10'
      source_dir:
        description: 'Directorio origen'
        required: true
        default: '/path/origen'
      dest_ip:
        description: 'IP destino'
        required: true
        default: '192.168.1.20'
      dest_dir:
        description: 'Directorio destino'
        required: true
        default: '/path/destino'
      port:
        description: 'Puerto SSH'
        required: true
        default: '22'

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      
      - name: Give execute permission to transfer script
        run: chmod +x ./scripts/transfer.sh

      - name: Run transfer script
        run: ./scripts/transfer.sh ${{ inputs.source_ip }} ${{ inputs.source_dir }} ${{ inputs.dest_ip }} ${{ inputs.dest_dir }} ${{ inputs.port }} ${{ secrets.SSH_PASSWORD }}
