name: Transfer Files via SFTP

on:
  workflow_dispatch:
    inputs:
      source_ip:
        description: "IP del servidor origen"
        required: true
        default: "192.168.1.1"
      source_path:
        description: "Ruta del directorio origen"
        required: true
        default: "/ruta/origen/"
      destination_ip:
        description: "IP del servidor destino"
        required: true
        default: "192.168.1.2"
      destination_path:
        description: "Ruta del directorio destino"
        required: true
        default: "/ruta/destino/"

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Transfer files from source to destination via SFTP
      run: |
        sshpass -p "${{ secrets.SOURCE_PASS }}" scp -o StrictHostKeyChecking=no -r \
        ${{ github.event.inputs.source_ip }}:${{ github.event.inputs.source_path }}/* \
        ${{ secrets.DEST_USER }}@${{ github.event.inputs.destination_ip }}:${{ github.event.inputs.destination_path }}
      env:
        SSHPASS: ${{ secrets.SOURCE_PASS }}
