name: Transfer Files

on:
  workflow_dispatch:
    inputs:
      ip_origen:
        description: 'IP origen'
        required: true
      ip_destino:
        description: 'IP destino'
        required: true
      dir_origen:
        description: 'Directorio origen'
        required: true
      dir_destino:
        description: 'Directorio destino'
        required: true

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ github.event.inputs.ip_origen }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ github.event.inputs.ip_destino }} >> ~/.ssh/known_hosts

      - name: Run transfer script
        run: |
          bash ./scripts/transfer.sh ${{ github.event.inputs.ip_origen }} ${{ github.event.inputs.ip_destino }} ${{ github.event.inputs.dir_origen }} ${{ github.event.inputs.dir_destino }}
