name: transfer

on:
  workflow_dispatch:
    inputs:
      source_ip:
        description: 'IP del servidor origen'
        required: true
      source_dir:
        description: 'Directorio origen'
        required: true
      dest_ip:
        description: 'IP del servidor destino'
        required: true
      dest_dir:
        description: 'Directorio destino'
        required: true
      username:
        description: 'Usuario SSH'
        required: true
      password:
        description: 'Contraseña SSH'
        required: true
      port:
        description: 'Puerto SFTP'
        required: false
        default: '22'

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Dar permisos al script
        run: chmod +x .pipeline/scripts/transfer.sh

      - name: Ejecutar script de transferencia por SFTP
        run: |
          .pipeline/scripts/transfer.sh \
            "${{ inputs.source_ip }}" \
            "${{ inputs.source_dir }}" \
            "${{ inputs.dest_ip }}" \
            "${{ inputs.dest_dir }}" \
            "${{ inputs.username }}" \
            "${{ inputs.password }}" \
            "${{ inputs.port }}"
